### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by stepand76** [toedter/jcalendar#1]
Hello,
I just encountered an issue with JCalendar. The month names are inflected. For example instead of October in Czech "Říjen", it shows "října".

![obrazek](https://user-images.githubusercontent.com/8308820/33434806-b2ddfb2e-d5e0-11e7-91c3-d1314bf197db.png)

Similar problem is described here: https://stackoverflow.com/questions/19466180/how-to-get-czech-name-of-month

I know the project is not updated but I would like to ask if there is a chance you provide a fixed version...

Thank you,
Stepan

**Comment by toedter** [comment]
Hi Stepan,

this might be a Java issue. Unfortunately I don't work on JCalendar anymore. If you find a fix for that, please let me know.

**Comment by stepand76** [comment]
Hi Kai,

As I am lazy to update your library I fixed it by this ugly hack:

public static void fixDateChooserMonthNames(JDateChooser dateChooser) {
        if (RswJavaUtils.getJavaSpecificationVersion() >= RswJavaUtils.JAVA_8) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("LLLL");
            Calendar calendar = Calendar.getInstance();
            JComboBox comboBox = (JComboBox) dateChooser.getJCalendar().getMonthChooser().getComboBox();
            comboBox.removeAllItems();
            for (int i = Calendar.JANUARY; i <= Calendar.DECEMBER; i++) {
                calendar.set(2000, i, 1);
                String monthName = RswStringUtils.capitalizeWord(simpleDateFormat.format(calendar.getTime()));
                //noinspection unchecked
                comboBox.addItem(monthName);
            }
        }
    }
